# -*- coding: utf-8 -*-
"""标准尾部模板 —— 全站唯一真源。

被两处共用，确保「每日新建」与「历史改造」产出的尾部完全一致：
  - scripts/build_report.py   （每日自动化构建）
  - scripts/unify_style.py    （历史报告批量统一）

标准尾部结构（所有报告完全相同，仅日报名与日期不同）：

      <div class="comments-section">
        <div class="comments-title">💬 评论区</div>
        <div class="comments-desc">登录 GitHub 账号即可评论，支持 Markdown 和表情回应。欢迎交流求职经验、分享面试心得！</div>
        <div class="giscus"></div>
      </div>
      </main>                     # 仅 <main> 型骨架有

    <footer class="footer">
      <p>{日报名} | 安徽工业大学机械工程硕士研究生个性化推荐报告</p>
      <p>报告日期：{N年N月N日} | 数据来源：公开网络信息整理</p>
      <div class="footer-meta">Generated by WorkBuddy Automation | Powered by TS-dinglilu.github.io</div>
    </footer>

    <button class="scroll-top" onclick="window.scrollTo({top:0,behavior:'smooth'})" aria-label="返回顶部">↑</button>

    <script>…scroll-top 监听 + giscus 动态挂载…</script>
    </body>
    </html>
"""

TITLE_SUFFIX = "安徽工业大学机械工程硕士研究生个性化推荐报告"

# 各分类的标准日报名 —— 全站唯一真源。
# 页脚（build_tail）、每日构建（build_report）与尾部统一（unify_style）都从这里取，
# 不要再从模板报告的 <h1> 派生：h1 属于页面自己的标题（允许带 emoji 或全称），
# 一旦拿它当页脚日报名，就会出现「构建出非标准名 → unify_style 修正 → 次日又漂移」的死循环。
CATEGORY_NAMES = {
    "car-recruit": "车企招聘日报",
    "mechanical-recruit": "机械招聘日报",
    "school-news": "校园新闻日报",
    "drone-research": "无人机科研日报",
    "ahut-campus": "安工大校园日报",
    "byd-recruit": "比亚迪招聘日报",
    "chery-recruit": "奇瑞招聘日报",
    "geely-recruit": "吉利招聘日报",
    "xiaomi-recruit": "小米汽车招聘日报",
    "weixiaoli-recruit": "蔚小理招聘日报",
    "traditional-auto": "传统车企招聘日报",
    "supply-chain-recruit": "车企供应链招聘日报",
    "research-institute": "科研院所招聘日报",
    "future-planning": "未来规划日报",
    "xuzhou-news": "徐州汽车机械日报",
    "nanjing-news": "南京汽车机械日报",
    "shanghai-news": "上海汽车机械日报",
    "hangzhou-news": "杭州汽车机械日报",
    "jiangzhehu-news": "江浙沪汽车机械日报",
    "hefei-news": "合肥汽车机械日报",
    "anhui-news": "安徽汽车机械日报",
    "jiangsu-news": "江苏汽车机械日报",
    "shenzhen-news": "深圳汽车机械日报",
    "xuzhou-recruit": "徐州招聘日报",
    "nanjing-recruit": "南京招聘日报",
    "shanghai-recruit": "上海招聘日报",
    "hangzhou-recruit": "杭州招聘日报",
    "jiangzhehu-recruit": "江浙沪招聘日报",
    "hefei-recruit": "合肥招聘日报",
    "anhui-recruit": "安徽招聘日报",
    "jiangsu-recruit": "江苏招聘日报",
    "shenzhen-recruit": "深圳招聘日报",
}

COMMENTS_BLOCK = (
    '<div class="comments-section">\n'
    '  <div class="comments-title">💬 评论区</div>\n'
    '  <div class="comments-desc">登录 GitHub 账号即可评论，支持 Markdown 和表情回应。欢迎交流求职经验、分享面试心得！</div>\n'
    '  <div class="giscus"></div>\n'
    '</div>'
)

# 尾部起点标记：任一在文件末尾窗口内出现，即视为「尾部区块从这里开始」。
# 注意：不含正文里的「评论区」字样（那是文章内容），只用注释 / 容器 / 页脚标签。
TAIL_MARKERS = [
    # —— 注释型 ——
    "<!-- 评论区 -->",
    "<!-- Giscus",
    "<!-- Giscus评论区",
    "<!-- ===== Giscus",
    "<!-- ====== Giscus",
    "<!-- Section 7: Giscus",
    "<!-- Section 11",
    "<!-- ======== Section 8: Giscus",
    # —— 容器型（务必带标签前缀，避免截断标签）——
    '<div class="comments-section',
    '<section class="comments-section',
    '<div class="giscus-section',
    '<section class="giscus-section',
    '<div class="giscus-container',
    '<div class="giscus-wrapper',
    '<div class="giscus"',
    '<div style="max-width:860px',
    'id="comments"',
    # —— 页脚型 ——
    '<div class="footer"',
    '<div class="footer-info"',
    '<div class="report-footer"',
    "<footer",
]

SEARCH_WINDOW = 9000  # 只在文件末尾这么多字符里找尾部标记，避免误伤正文

# 「信息来源」板块可能的起始标签（按"距『信息来源』最近者优先"取用）
SRC_BLOCK_STARTS = ['<div class="section"', '<div class="section ', '<footer',
                    '<div class="footer"', '<div class="footer-info"', '<div class="sources"',
                    '<div class="container"', '<section']

# 需要"降级"为普通 section 的页脚包裹标签（保留内容，去掉页脚外壳）
FOOTER_WRAPPERS = ["<footer", '<div class="footer"', '<div class="footer-info"',
                   '<div class="report-footer"']


def build_tail(name, y, m, d, giscus_script, has_main_close=True,
               extra_close=0, preserve_html=""):
    """生成标准尾部文本（从评论区之前开始，到 </html> 结束）。

    name          : 日报中文名，如「车企招聘日报」
    has_main_close: 骨架是否为 <main> 型（需要在评论区后补 </main>）
    extra_close   : 需要前置的 </div> 个数（补偿被替换区间内多出来的容器闭合）
    preserve_html : 需原样保留在评论区之前的原文块（通常是「信息来源汇总」）
    """
    parts = []
    if extra_close > 0:
        parts.append("</div>\n" * extra_close)
    if preserve_html:
        parts.append(preserve_html.rstrip() + "\n\n")
    parts.append(COMMENTS_BLOCK + "\n")
    if has_main_close:
        parts.append("</main>\n")
    parts.append(
        "\n<footer class=\"footer\">\n"
        "  <p>%s | %s</p>\n"
        "  <p>报告日期：%d年%d月%d日 | 数据来源：公开网络信息整理</p>\n"
        "  <div class=\"footer-meta\">Generated by WorkBuddy Automation | Powered by TS-dinglilu.github.io</div>\n"
        "</footer>\n\n"
        "<button class=\"scroll-top\" onclick=\"window.scrollTo({top:0,behavior:'smooth'})\" aria-label=\"返回顶部\">↑</button>\n\n"
        "%s\n</body>\n</html>\n" % (name, TITLE_SUFFIX, y, m, d, giscus_script)
    )
    return "".join(parts)


import re as _re

_DIV_RE = _re.compile(r"<div\b|</div>")
# 正文里可能残留的「旧评论区」容器（带标签前缀，避免截断标签）
_LEGACY_CONTAINERS = [
    '<div class="comments-section',
    '<section class="comments-section',
    '<div class="giscus-section',
    '<section class="giscus-section',
    '<div class="giscus-container',
    '<section class="giscus-container',
    '<div class="giscus-wrapper',
    '<div style="max-width:860px',
]
_INLINE_GISCUS = _re.compile(
    r'<script[^>]*src="https://giscus\.app/client\.js"[^>]*>\s*</script>\s*', _re.S)
_CMT_TAIL_RE = _re.compile(r"<!--[^>]*(?:giscus|评论区|Comments?)[^>]*-->\s*", _re.I)
_BARE_GISCUS = _re.compile(r'\n?<div class="giscus"></div>\s*')


def _match_div(s, start):
    """s[start] 处是 '<div'，返回配对 '</div>' 之后的偏移；失败返回 -1。"""
    depth = 0
    for m in _DIV_RE.finditer(s, start):
        if m.group(0) == "</div>":
            depth -= 1
            if depth == 0:
                return m.end()
        else:
            depth += 1
    return -1


def _match_section(s, start):
    """s[start] 处是 '<section'，返回配对 '</section>' 之后的偏移；失败返回 -1。"""
    ore = _re.compile(r"<section\b")
    cre = _re.compile(r"</section>")
    depth, pos = 0, start
    while True:
        mo, mc = ore.search(s, pos), cre.search(s, pos)
        if mo is None and mc is None:
            return -1
        if mo is not None and (mc is None or mo.start() < mc.start()):
            depth += 1
            pos = mo.end()
        else:
            depth -= 1
            if depth == 0:
                return mc.end()
            pos = mc.end()


def _elem_end(s, i):
    """i 为元素起始 '<' 处，按标签类型返回配对结束位置；失败 -1。"""
    if s.startswith("<section", i):
        return _match_section(s, i)
    if s.startswith("<div", i):
        return _match_div(s, i)
    return -1


def strip_comment_artifacts(html):
    """删除正文中残留的旧评论区（容器 + 内联 giscus 脚本 + 相关注释），返回 (html, 删除数量)。

    用于两处：① 构造阶段清理内容源；② 改造阶段清理尾部区间之前的残留旧评论区。
    """
    removed = 0
    for _ in range(30):
        hit = None
        for pat in _LEGACY_CONTAINERS:
            i = html.find(pat)
            if i != -1:
                hit = i
                break
        if hit is None:
            j = html.find('id="comments"')
            if j != -1:
                lt = html.rfind("<", max(0, j - 240), j)
                if lt != -1 and html.startswith("<div", lt):
                    hit = lt
        if hit is None:
            break
        end = _elem_end(html, hit)
        if end == -1:
            break
        html = html[:hit] + html[end:]
        removed += 1

    for _ in range(4):
        new = _INLINE_GISCUS.sub("", html)
        if new == html:
            break
        removed += 1
        html = new
    for _ in range(6):
        new = _CMT_TAIL_RE.sub("", html)
        if new == html:
            break
        html = new
    # 裸的 giscus 占位（旧尾部残留）
    new = _BARE_GISCUS.sub("\n", html)
    if new != html:
        removed += 1
        html = new
    return html, removed


def demote_footer_wrapper(block):
    """把被保留的「信息来源」块的外层页脚标签降级为 <div class="section">，避免出现双页脚。"""
    block = block.strip()
    for w in FOOTER_WRAPPERS:
        if block.startswith(w):
            gt = block.find(">")
            if gt == -1:
                return block
            inner = block[gt + 1:]
            close = "</footer>" if w.startswith("<footer") else "</div>"
            if inner.rstrip().endswith(close):
                inner = inner.rstrip()[: -len(close)]
            return '<div class="section">\n' + inner.strip() + "\n</div>"
    return block
